---
title: "PID_preliminary_data"
author: "Cath Burke"
date: "14 February 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r load pacakages}
library("phyloseq")
library("ggplot2")
library("vegan")
library("reshape2")
library("tidyverse")
library("dplyr")
library("philentropy")
library("heatmaply")

```
```{r load data into phyloseq}
biom<-"data/otu_table_mc2_w_tax_no_pynast_failures_json.biom"
map<-read.table("data/PID_map.txt", header=TRUE, stringsAsFactors=TRUE, sep="\t", row.names=1)
tree<-read_tree("data/rep_set.tre")
tax<- read.table("data/PID_taxtable.txt", header=TRUE, sep="\t", row.names=1)
tax<-as.matrix(tax)
tax<-tax_table(tax)
PID_map<-sample_data(map)
PID<-import_biom(biom, treefilename=tree)
PID<-merge_phyloseq(PID,PID_map,tax)
tax_table(PID)<-tax_table(PID)[,8:15]
#The last two columns in the tax table are the STIRRUPS classifications, the others are the RDP classficiations
#Remove samples with less than 2K seqs
PID_fil<-prune_samples(sample_sums(PID) > 2000, PID)
PID_fil<-filter_taxa(PID_fil, function(x) sum(x)>9, TRUE)
PID_fil_rare<-rarefy_even_depth(PID_fil, 2000, rngseed=711, replace=FALSE, trimOTUs=TRUE)
#Set colour pallette
mycol <- palette(c("#e6194b","#3cb44b","#ffe119","#0082c8","#f58231","#911eb4","#46f0f0","#f032e6","#d2f53c","#fabebe","#008080","#e6beff","#aa6e28","#fffac8","#800000","#aaffc3","#808000","#ffd8b1","#000080","#808080","#FFFFFF","#000000"))
mycol <- palette(c("#e6194b","#3cb44b","#ffe119","#0082c8","#f58231","#911eb4","#46f0f0","#f032e6","#d2f53c","#fabebe","#008080","#e6beff","#aa6e28","#fffac8","#800000","#aaffc3","#808000","#ffd8b1","#000080","#808080","#FFFFFF","#000000"))

```
#Cluster into community state types

```{r pressure, echo=FALSE}


#Convert counts to relative abundance
PID_fil_rel<-transform_sample_counts(PID_fil, function(x) x/sum(x))
#Need to merge OTUs with the same species assignment.  Because the RDP tax strings don't always match at the higher levels for the STIRRUPs assignments, need to remove other columns from tax table for the merging to occur properly.
PID_merge_count<-PID_fil
tax_table(PID_merge_count)<-tax_table(PID_merge_count)[,c(1,8)]
PID_merge_count<-tax_glom(PID_merge_count, taxrank="s_Genus_s_Species")

PID_merge<-PID_fil_rel
tax_table(PID_merge)<-tax_table(PID_merge)[,c(1,8)]
PID_merge<-tax_glom(PID_merge, taxrank="s_Genus_s_Species")
PID_merge
PID_merge_samples<-subset_samples(PID_merge, sample_type %in% c("patient","cst_control"))
#Top20
Top20OTUs = names(sort(taxa_sums(PID_merge_samples), TRUE)[1:20])
PID_fil_t20<-prune_taxa(Top20OTUs,PID_merge_samples)
#First replace 0 with 1 in otu_table
otus<-otu_table(PID_fil_t20)
otus[otus==0]<-1
PID_log<-PID_fil_t20
otu_table(PID_log)[otu_table(PID_log)==0]<-1
#phyloseq heat map ordered by ordination rather than clustering
PID_rel_t20<-transform_sample_counts(PID_merge_samples, function(x) x/sum(x))
PID_rel_t20<-prune_taxa(Top20OTUs,PID_rel_t20)
plot_heatmap(PID_rel_t20, method="MDS", distance="jsd",sample.label="disease_status", taxa.label="s_Genus_s_Species", taxa.order="s_Genus_s_Species", trans=log_trans(2),low="#66CCFF", high="#000033",na.value="white")
#Base R heatmap with default dist and clustering
heatmap(otu_table(PID_fil_t20), labRow=(data.frame(tax_table(PID_fil_t20))$s_Genus_s_Species), labCol=sample_data(PID_fil_t20)$disease_status)
#Hierarchical clustering
otu<-otu_table(PID_rel_t20)
row.names(otu)<-data.frame(tax_table(PID_rel_t20))$s_Genus_s_Species
js_d<-phyloseq::distance(PID_rel_t20, method="jsd", TRUE)
hc<-hclust(js_d, method="ward.D")
heatmaply(otu, Colv=hc,
          seriate="mean", col_side_colors=data.frame(sample_data(PID_fil_t20)[,c(2,5,7)]), fontsize_row = 6, fontsize_col = 6,
          plot_method="ggplot")


d<-JSD(data.frame(otus), est.prob="empirical")
heatmap(d)

phyloseq::JSD(PID_fil_t20)
#Produces a distance matrix between OTUs rather than samples.
hc<-hclust(as.dist(d), method="ward.D")
hc2<-hclust(data.frame(otus), method="ward.D")
plot(hc2)

```

#Taxa summaries

```{r}
PID_smelt<-psmelt(PID_merge)
PID_smelt<- PID_smelt %>% group_by(sample_name) %>% mutate(perc_abund=Abundance/sum(Abundance)*100)

PID_smelt %>% filter(disease_status %in% c("Case","Control")) %>%
  filter(Abundance>0.05)%>%
  ggplot(aes(x=sample_name, y=rel_abund, fill=s_Genus_s_Species))+
  geom_bar(stat="identity") +
  facet_grid(.~disease_status, scales="free")+
  scale_fill_manual(values = mycol)

#Community state type II has no Lactobacillus inners - looking at the controls now to examine this further.

#Look at number of seqs for cst samples
PID_smelt %>% filter(sample_type=="cst_control") %>% group_by(sample_name) %>% summarise (sum=sum(Abundance))

#Check Lactobacillus OTUs in CSTII
PID_smelt %>% filter(sample_name=="CST2C") %>% filter(Genus=="g__Lactobacillus") %>% select(OTU,Abundance, rel_abund,Genus,Species,s_Genus_s_Species) %>% arrange

#Export OTU table from tax_glom for use in correlation analysis in QIIME.
#Check that rows are in the same order for tax and otu tables
t1<-row.names(otu_table(PID_merge_count))
t2<-row.names(tax_table(PID_merge_count))
identical(t1,t2)
glom_otus<-data.frame(otu_table(PID_merge_count))
row.names(glom_otus)<-data.frame(tax_table(PID_merge_count))$s_Genus_s_Species
write.table(glom_otus, file="glom_otu.txt", sep="\t",quote=FALSE)
#Had to make a few changes to the txt file to make it suitable for conversion to biom table and qiime use.  Add #OTUId as first column header, change underscores in speceis names to .
sort(sample_names(PID_merge_count))
#Prevotella has a non-significant increase in PID.  Plot and take a look
PID_smelt %>% filter(s_Genus_s_Species=="Prevotella_melaninogenica_cluster") %>%
  filter(sample_type=="patient") %>%
  ggplot(aes(x=Sample, y=perc_abund))+geom_bar(stat="identity")+
  facet_grid(.~disease_status, scales="free", space="free")+labs(title="Prevotella melaninogenica cluster relative abundance", x=NULL, y="Relative abundance (%)") + theme(axis.text.x = element_text(angle = 90))

PID_smelt %>% filter(s_Genus_s_Species=="Lactobacillus_crispatus_cluster") %>%
  filter(sample_type=="patient") %>%
  ggplot(aes(x=Sample, y=perc_abund))+geom_bar(stat="identity")+
  facet_grid(.~disease_status, scales="free", space="free")+labs(title="Lactobacillus_crispatus_cluster relative abundance", x=NULL, y="Relative abundance (%)") + theme(axis.text.x = element_text(angle = 90))

PID_smelt %>% filter(s_Genus_s_Species %in% c("Lachnospiraceae_BVAB1", "Megasphaera_micronuciformis","Eggerthella_sinensis","Aerococcus_christensenii","Atopobium_vaginae","Parvimonas_micra","Prevotella_cluster2","Dialister_micraerophilus","Sneathia_amnii")) %>%
  filter(sample_type=="patient") %>%
  filter(!is.na(pos_chlamydia)) %>%
  ggplot(aes(x=Sample, y=perc_abund, fill=s_Genus_s_Species))+
  geom_bar(stat="identity")+
  facet_grid(.~pos_chlamydia, scales="free", space="free")+
  labs(x=NULL, y="Relative abundance (%)") + 
  theme(axis.text.x = element_text(angle = 90))

PID_smelt_full<-psmelt(PID_fil_rare)
PID_smelt_full<- PID_smelt_full %>% group_by(sample_name) %>% mutate(rel_abund=Abundance/sum(Abundance))
PID_smelt_full %>% filter(Genus=="g__Prevotella") %>%
  filter(sample_type=="patient") %>%
  ggplot(aes(x=Sample, y=Abundance))+geom_bar(stat="identity")+
  facet_grid(cst~disease_status, scales="free")+labs(x=NULL, y="Relative abundance (%)") + theme(axis.text.x = element_text(angle = 90))

```
#Beta-div
```{r}
PID_merge_pat<-subset_samples(PID_merge, sample_type=="patient")
dist<-phyloseq::distance(PID_merge_pat, "jsd")
dist_ord<-ordinate(PID_merge_pat, method="PCoA", distanct=dist)
plot_ordination(PID_merge_pat,dist_ord, color="disease_status", shape="cst")
```

